#!/bin/sh

show_help() {
	echo "Usage:"
	echo "  cgi-cookie [-a] <dir> [<name>]"
	echo
	echo "Options:"
	echo "  -a       List all cookies."
	echo "  <dir>    CGI data directory."
	echo "  <name>   Name of cookie."
	echo
	echo "Example:"
	echo "  cgi-cookie \"\$cgi\" sessionId"
}

listall=false

while getopts ah opt
do
	case $opt in
		a)
			listall=true
			;;
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if test "$#" -lt 1
then
	echo "Not enough arguments" >&2
	show_help
	exit 1
fi

dir=$1

if $listall
then
	find "$dir/cookies" -type f -printf '%f\n' 2>/dev/null | while read name
	do
		echo "$(urlencode -d "$name")"
	done
else
	name=$(urlencode "$2")

	cat "$dir/cookies/$name" 2>/dev/null
fi
