#!/bin/sh

show_help() {
	echo "Usage: cgi-free"
	echo
	echo "Environment variables:"
	echo "  SHCGI  CGI data directory to free."
	echo
	echo "Example:"
	echo "  cgi-free"
}

while getopts h opt
do
	case $opt in
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

rm -rf "$SHCGI"
