#!/bin/sh

show_help() {
	echo "Usage: cgi-free <dir>"
	echo
	echo "Options:"
	echo "  <dir>  CGI data directory to free."
	echo
	echo "Example:"
	echo "  cgi-free \"\$cgi\""
}

while getopts h opt
do
	case $opt in
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if test "$#" -lt 1
then
	echo "Not enough arguments" >&2
	show_help
	exit 1
fi

dir=$1

rm -rf "$dir"
