#!/bin/sh

: ${SHCGI_KEEPALIVE_INTERVAL:=30}
: ${SHCGI_KEEPALIVE_TICK:=1}

running() {
	ps -p $1 >/dev/null 2>&1
}

show_help() {
	echo "Usage: cgi-keep-alive [-bh] <pid> <message>"
	echo
	echo "Options:"
	echo "  -b  Send message as-is instead of formatting it as a header."
	echo "  -h  Show usage message."
	echo "  <pid>          PID to wait on."
	echo "  <message>      Message to send."
	echo
	echo "Environment variables:"
	echo "  SHCGI_KEEPALIVE_INTERVAL  How often in ticks to send a keep-alive message. Default is ${SHCGI_KEEPALIVE_INTERVAL}."
	echo "  SHCGI_KEEPALIVE_TICK      How long in seconds the program waits between checking the status of the PID. Default is ${SHCGI_KEEPALIVE_TICK}."
}

format_as_header=true

while getopts bh opt
do
	case $opt in
		b)
			format_as_header=false
			;;
		?)
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

pid=$1
message=${2:-'<!-- -->'}

i=0

while running "$pid"
do
	if test $((i % $SHCGI_KEEPALIVE_INTERVAL)) = 0
	then
		if $format_as_header
		then
			cgi-header -n "CGI-Keep-Alive: $message"
		else
			echo "$message"
		fi
	fi

	sleep $SHCGI_KEEPALIVE_TICK

	i=$((i + 1))
done
