#!/bin/sh

show_help() {
	echo "Usage: cgi-param [-a] <dir> [<name>]"
	echo
	echo "Options:"
	echo "  -a      List all parameters."
	echo "  <dir>   CGI data directory."
	echo "  <name>  Name of param."
	echo
	echo "Example:"
	echo "  cgi-param \"\$cgi\" name"
}

listall=false

while getopts ah opt
do
	case $opt in
		a)
			listall=true
			;;
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if test "$#" -lt 1
then
	echo "Not enough arguments" >&2
	show_help
	exit 1
fi

dir=$1

if $listall
then
	find "$dir/params" -type f -printf '%f\n' 2>/dev/null | while read name
	do
		echo "$name"
	done
else
	name=$2

	cat "$dir/params/$name" 2>/dev/null
fi
