#!/bin/sh

show_help() {
	echo "Usage:"
	echo "  cgi-cookie (-a | <name> [<value>])"
	echo
	echo "Options:"
	echo "  -a       List all cookies."
	echo "  <name>   Name of cookie."
	echo "  <value>  Set a value for the named cookie."
	echo
	echo "Environment variables:"
	echo "  SHCGI                The directory returned by cgi-init."
	echo "  SHCGI_COOKIE_DOMAIN  The domain used for cookies."
	echo "  SHCGI_COOKIE_PATH    The path used for cookies."
	echo
	echo "Example:"
	echo "  cgi-cookie sessionId"
	echo "  cgi-cookie theme light"
}

listall=false

while getopts ah opt
do
	case $opt in
		a)
			listall=true
			;;
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if $listall
then
	find "$SHCGI/cookies" -type f -printf '%f\n' 2>/dev/null | while read name
	do
		echo "$(urlencode -d "$name")"
	done
elif test $# = 1
then
	cat "$SHCGI/cookies/$1" 2>/dev/null
elif test $# = 2
then
	header="Set-Cookie: $1=$2"

	if test -n "$SHCGI_COOKIE_DOMAIN"
	then
		header+="; Domain=$SHCGI_COOKIE_DOMAIN"
	fi

	if test -n "$SHCGI_COOKIE_PATH"
	then
		header+="; Path=$SHCGI_COOKIE_PATH"
	fi

	cgi-header -n "$header"
else
	echo 'Invalid number of arguments.' >&2
	show_help
	exit 1
fi
