#!/bin/sh

show_help() {
	echo "Usage:"
	echo "  cgi-cookie <dir> <name>"
	echo
	echo "Options:"
	echo "  <dir>    CGI data directory."
	echo "  <name>   Name of cookie."
	echo
	echo "Example:"
	echo "  cgi-cookie \"\$cgi\" sessionId"
}

while getopts ahs opt
do
	case $opt in
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if test "$#" -lt 2
then
	echo "Not enough arguments" >&2
	show_help
	exit 1
fi

dir=$1
name=$2

cat "$dir/cookies/$name" 2>/dev/null
