#!/bin/sh

CGI_WAIT_INTERVAL=${CGI_WAIT_INTERVAL:-30}
CGI_WAIT_TICK=${CGI_WAIT_TICK:-1}

running() {
	ps -p $1 >/dev/null 2>&1
}

show_help() {
	echo "Usage: cgi-keep-alive [-bh] <pid> <message>"
	echo
	echo "Options:"
	echo "  -b  Send message as-is instead of formatting it as a header."
	echo "  -h  Show usage message."
	echo "  <pid>          PID to wait on."
	echo "  <message>      Message to send."
}

format_as_header=true

while getopts bhi:t: opt
do
	case $opt in
		b)
			format_as_header=false
			;;
		h|\?)
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

pid=$1
message=${2:-'<!-- -->'}

i=0

while running "$pid"
do
	if test $((i % CGI_WAIT_INTERVAL)) = 0
	then
		if $format_as_header
		then
			cgi-header -n "CGI-Keep-Alive: $message"
		else
			echo "$message"
		fi
	fi

	sleep "$CGI_WAIT_TICK"

	i=$((i + 1))
done
