#!/bin/sh

show_help() {
	echo "Usage: cgi-param (-a | <name>)"
	echo
	echo "Options:"
	echo "  -a      List all parameters."
	echo "  <name>  Name of param."
	echo
	echo "Environment variables:"
	echo "  SHCGI  The directory returned by cgi-init."
	echo
	echo "Example:"
	echo "  cgi-param \"\$cgi\" name"
}

listall=false

while getopts ah opt
do
	case $opt in
		a)
			listall=true
			;;
		h|'?')
			show_help
			exit
			;;
	esac
done
shift $((OPTIND - 1))

if $listall
then
	find "$SHCGI/params" -type f -printf '%f\n' 2>/dev/null | while read name
	do
		echo "$name"
	done
elif test $# = 1
then
	cat "$SHCGI/params/$1" 2>/dev/null
fi
