#!/bin/sh

if test "$2"
then
	sendheaders -n "Set-Cookie: $1=$2"
else
	echo "$HTTP_COOKIE" | tr '=;' '\t\n' | while read key val
	do
		if test "$1" = "$key"
		then
			echo "$val"
			break
		fi
	done
fi
